
pass0 = [
	# Agricultural
	"AG.PRD.CROP.XD",
	"AG.YLD.CREL.KG",
	"AG.LND.AGRI.ZS",
	"AG.LND.CREL.HA",
	"SN.ITK.DEFC.ZS",
	"AG.LND.IRIG.AG.ZS",
	"AG.LND.AGRI.ZS",
	"AG.LND.AGRI.K2",
	"FP.CPI.TOTL",
	"SL.AGR.EMPL.ZS",
	"AG.LND.PRCP.MM",
	"AG.LND.CROP.ZS",

	# Terrorism
	"VC.BTL.DETH",
	"SH.STA.FGMS.ZS",
	"SP.HOU.FEMA.ZS",
	"NY.GDP.MKTP.KD",
	"NY.GDP.PCAP.KD",

	# Climate
	"ER.H2O.INTR.PC",
	"EN.CLC.MDAT.ZS",
	"SL.AGR.EMPL.ZS",
	"SL.EMP.TOTL.SP.FE.NE.ZS",
	"SL.EMP.TOTL.SP.MA.ZS",
	"NY.GNP.PCAP.KD",
	"NY.GNP.MKTP.KD.ZG",
	"SL.UEM.TOTL.ZS",
	"SL.TLF.CACT.FE.ZS",
	"SM.POP.REFG",
	"SM.POP.REFG.OR",
	"VC.IDP.TOCV",
	"AG.PRD.LVSK.XD",

	# Investment"
	"SP.ADO.TFRT",
	"SH.STA.BASS.UR.ZS",
	"EG.ELC.ACCS.UR.ZS",
	"SH.STA.BASS.RU.ZS",
	"EG.ELC.ACCS.RU.ZS",
	"SH.H2O.BASW.UR.ZS",
	"SP.POP.0014.TO",
	"EN.POP.DNST",
	"SP.POP.GROW",
	"SP.DYN.CBRT.IN",
	"HD.HCI.OVRL",
	"SH.XPD.CHEX.PC.CD",
	"SE.XPD.TOTL.GB.ZS",
	"SE.XPD.CTOT.ZS	",

	# FUNDING
	"VC.PKP.TOTL.UN",
	"DT.NFL.FAOG.CD",
	"DT.NFL.IAEA.CD",
	"DT.NFL.IFAD.CD",
	"DT.NFL.ILOG.CD",
	"DT.NFL.UNAI.CD",
	"DT.NFL.UNDP.CD",
	"DT.NFL.UNFP.CD",
	"DT.NFL.UNCR.CD",
	"DT.NFL.UNCF.CD",
	"DT.NFL.UNPB.CD",
	"DT.NFL.UNRW.CD",
	"DT.NFL.UNTA.CD",
	"DT.NFL.UNWT.CD",
	"DT.NFL.WFPG.CD",
	"DT.NFL.WHOL.CD"
]

test = [
	"SL.EMP.TOTL.SP.FE.NE.ZS",
	"SL.EMP.TOTL.SP.MA.ZS"
]

inds = pass0
htmlHeader = "pass0"
